name: 'Deploy to Dokku'

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Cloning repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Push to dokku
      uses: obrassard/action-dokku-deploy@v1.0.1
      with:
        dokku_repo: 'ssh://dokku@myside.app:22/inw-stock-photos-strapi'
        ssh_key: ${{ secrets.SSH_KEY }}
        deploy_branch: 'main'
